name: ai-travel-agents
services:
  tool-customer-query:
    container_name: tool-customer-query
    build: packages/tools/customer-query
    ports:
      - "5001:8080"
    environment:
      - OTEL_SERVICE_NAME=tool-customer-query
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889

  tool-destination-recommendation:
    container_name: tool-destination-recommendation
    build: packages/tools/destination-recommendation
    ports:
      - "5002:8080"

  tool-itinerary-planning:
    container_name: tool-itinerary-planning
    build: packages/tools/itinerary-planning
    ports:
      - "5003:8000"

  tool-echo-ping:
    container_name: tool-echo-ping
    build: packages/tools/echo-ping
    ports:
      - "5004:3000"
    depends_on:
      - aspire-dashboard
    env_file:
      - "./packages/tools/echo-ping/.env"
      - "./packages/tools/echo-ping/.env.docker" # override .env with .env.docker

  web-api:
    container_name: web-api
    build: ./packages/api
    ports:
      - "4000:4000"
    depends_on:
      - tool-customer-query
      - tool-destination-recommendation
      - tool-itinerary-planning
      - tool-echo-ping
    env_file:
      - "./packages/api/.env"
      - "./packages/api/.env.docker" # override .env with .env.docker
    environment:
      - IS_LOCAL_DOCKER_ENV=true 
      - DEBUG=true # Enable Azure JS SDK debug logging
  
  web-api-python:
    container_name: api-python
    build: ./packages/api-python
    ports:
      - "4000:4000"
    depends_on:
      - tool-customer-query
      - tool-destination-recommendation
      - tool-itinerary-planning
      - tool-echo-ping
    env_file: 
      - "./packages/api-python/.env"
      - "./packages/api-python/.env.docker" # override .env with .env.docker
    environment:
      - IS_LOCAL_DOCKER_ENV=true 
      - DEBUG=true # Enable Azure JS SDK debug logging


  web-ui:
    container_name: web-ui
    build: ./packages/ui
    ports:
      - "4200:4200"
    depends_on:
      - web-api
    env_file: 
      - "./packages/api/.env"
      - "./packages/api/.env.docker" # override .env with .env.docker

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - 18888:18888
      - 4317:18889
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  llm:
    provider:
      type: model
      options:
        model: ${DOCKER_MODEL:-ai/phi4:14B-Q4_0}