name: ai-travel-agents
services:
  mcp-customer-query:
    container_name: mcp-customer-query
    build: packages/mcp-servers/customer-query
    ports:
      - "5001:8080"
    environment:
      - OTEL_SERVICE_NAME=mcp-customer-query
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889

  mcp-destination-recommendation:
    container_name: mcp-destination-recommendation
    build: packages/mcp-servers/destination-recommendation
    ports:
      - "5002:8080"

  mcp-itinerary-planning:
    container_name: mcp-itinerary-planning
    build: packages/mcp-servers/itinerary-planning
    ports:
      - "5003:8000"

  mcp-echo-ping:
    container_name: mcp-echo-ping
    build: packages/mcp-servers/echo-ping
    ports:
      - "5004:3000"
    env_file:
      - "./packages/mcp-servers/echo-ping/.env"
      - "./packages/mcp-servers/echo-ping/.env.docker" # override .env with .env.docker

  api-langchain-js:
    container_name: api-langchain-js
    build: ./packages/api-langchain-js
    ports:
      - "4000:4000"
    env_file:
      - "./packages/api-langchain-js/.env"
      - "./packages/api-langchain-js/.env.docker" # override .env with .env.docker
    environment:
      - IS_LOCAL_DOCKER_ENV=true 
      - DEBUG=true # Enable Azure JS SDK debug logging
  
  
  api-llamaindex-ts:
    container_name: api-llamaindex-ts
    build: ./packages/api-llamaindex-ts
    ports:
      - "4001:4001"
    env_file:
      - "./packages/api-llamaindex-ts/.env"
      - "./packages/api-llamaindex-ts/.env.docker" # override .env with .env.docker
    environment:
      - IS_LOCAL_DOCKER_ENV=true 
      - DEBUG=true # Enable Azure JS SDK debug logging
  
  api-maf-python:
    container_name: api-maf-python
    build: ./packages/api-maf-python
    ports:
      - "4010:4010"
    env_file: 
      - "./packages/api-maf-python/.env"
      - "./packages/api-maf-python/.env.docker" # override .env with .env.docker
    environment:
      - IS_LOCAL_DOCKER_ENV=true 
      - DEBUG=true # Enable Azure JS SDK debug logging


  ui-angular:
    container_name: ui-angular
    build: ./packages/ui-angular
    ports:
      - "4200:4200"
    env_file: 
      - "./packages/ui-angular/.env"
      - "./packages/ui-angular/.env.docker" # override .env with .env.docker

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - 18888:18888
      - 4317:18889
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  llm:
    provider:
      type: model
      options:
        model: ${DOCKER_MODEL:-ai/phi4:14B-Q4_0}