[project]
name = "itinerary-planning-mcp-server"
version = "0.1.0"
description = "A working example of an MCP server for itinerary planning."
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "starlette>=0.46.1",
    "uvicorn>=0.34.0"
]

[project.scripts]
start = "server:run"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.ruff]
line-length = 120
target-version = "py313"
select = ["E", "F", "I", "UP", "A"]
ignore = ["D203"]