services:
  customer-query-agent:
    container_name: customer-query-agent
    build: ./agents/customer-query-agent
    ports:
      - "5001:5000"
    environment:
      - AGENT_NAME=customer-query-agent
    networks:
      - ai-network

  destination-recommendation-agent:
    container_name: destination-recommendation-agent
    build: ./agents/destination-recommendation-agent
    ports:
      - "5002:5000"
    networks:
      - ai-network

  itinerary-planning-agent:
    container_name: itinerary-planning-agent
    build: ./agents/itinerary-planning-agent
    ports:
      - "5003:5000"
    networks:
      - ai-network

  code-evaluation-agent:
    container_name: code-evaluation-agent
    build: ./agents/code-evaluation-agent
    ports:
      - "5004:5000"
    networks:
      - ai-network

  model-inference-agent:
    container_name: model-inference-agent
    build: ./agents/model-inference-agent
    ports:
      - "5005:5000"
    networks:
      - ai-network

  echo-agent:
    container_name: echo-agent
    build: ./agents/echo-agent
    ports:
      - "5006:5000"
    networks:
      - ai-network
    environment:
      - OTEL_SERVICE_NAME=echo-agent
      - OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTLP_HEADERS=x-otlp-header=header-value

  api:
    container_name: api
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - customer-query-agent
      - destination-recommendation-agent
      - itinerary-planning-agent
      - code-evaluation-agent
      - model-inference-agent
      - echo-agent
    networks:
      - ai-network
    environment:
      - OTEL_SERVICE_NAME=api
      - OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTLP_HEADERS=x-otlp-header=header-value

  ui:
    container_name: ui
    build: ./ui
    ports:
      - "8000:8000"
    depends_on:
      - api
    networks:
      - ai-network

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - 18888:18888
      - 4317:18889
    networks:
      - ai-network
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

networks:
  ai-network:
    driver: bridge