name: AI OpSec Agent

on:
  workflow_dispatch:
  pull_request:
    paths: 
    - "**/*.py"
    - "**/*.js"
    - "**/*.ts"
    - "**/*.java"
    - "**/*.cs" 
    - "**/*.bicep"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"


permissions:
  contents: read
  pull-requests: write # so we can comment on PRs

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: Azure-Samples/azure-ai-travel-agents/.github/workflows/ai-opsec-agent@main

