name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api-langchain:
    name: API LangChain.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/api-langchain-js
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build

  build-api-llamaindex:
    name: API LlamaIndex.TS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/api-llamaindex-ts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build

  build-api-maf-python:
    name: API Microsoft Agent Framework (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/api-maf-python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip
      - run: pip install -e .

  build-ui-angular:
    name: UI Angular
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui-angular
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build

  build-customer-query:
    name: MCP Customer Query (.NET)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mcp-servers/customer-query
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore

  build-destination-recommendation:
    name: MCP Destination Recommendation (Java)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mcp-servers/destination-recommendation
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - run: mvn clean install -DskipTests

  build-echo-ping:
    name: MCP Echo Ping (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mcp-servers/echo-ping
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build

  build-itinerary-planning:
    name: MCP Itinerary Planning (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/mcp-servers/itinerary-planning
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
